### ISSUE TITLE
[Feature]: F-Droid

### ISSUE THREAD

**Issue by anonimo82** [AndroidIDEOfficial/AndroidIDE#545]
### Feature description

This is a suggestion more than a request: you could distribute AndroidIDE on F-Droid.

### What version of AndroidIDE you're using?

v2.1.1

### Duplicate issues

- [ ] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I'll publish it soon. But this is a duplicate of #419.

**Comment by anonimo82** [comment]
Sorry, please forgive me

**Comment by matan-h** [comment]
the issue "#419" is not found . is there an updated link?

**Comment by yzqzss** [comment]
Is there any progress?
:)

**Comment by itsaky** [comment]
I've tried to publish AndroidIDE to F-Droid multiple times, but it always fails to determine the version of AndroidIDE from the source code.

However, we might consider creating a custom F-Droid repository which can be used to publish AndroidIDE. After that, you'll be able to add that repository to the F-Droid client.

**Comment by yzqzss** [comment]
> I've tried to publish AndroidIDE to F-Droid multiple times, but it always fails to determine the version of AndroidIDE from the source code.

Could you paste out your f-droid-data .yml build file?  Maybe I or someone else can help. :)

**Comment by itsaky** [comment]
> > I've tried to publish AndroidIDE to F-Droid multiple times, but it always fails to determine the version of AndroidIDE from the source code.
> 
> Could you paste out your f-droid-data .yml build file? Maybe I or someone else can help. :)

Unfortunately, I don't have the files now. Sorry.

However, the "fastlane" directory in the repository contains some basic information about the project which you can use to create the metadata if you want.

**Comment by linsui** [comment]
> You should also note that the AndroidIDE project now uses product flavors to separate the assets and reduce the APK size. I don't know if F-Droid supports product flavors (with same package name).

Do you mean this? https://github.com/AndroidIDEOfficial/AndroidIDE/blob/b40d52e6cf23d01a14cef7a6a6a3ce1345167ddc/common/src/main/java/com/itsaky/androidide/app/configuration/CpuArch.kt

**Comment by itsaky** [comment]
> > You should also note that the AndroidIDE project now uses product flavors to separate the assets and reduce the APK size. I don't know if F-Droid supports product flavors (with same package name).
> 
> Do you mean this? https://github.com/AndroidIDEOfficial/AndroidIDE/blob/b40d52e6cf23d01a14cef7a6a6a3ce1345167ddc/common/src/main/java/com/itsaky/androidide/app/configuration/CpuArch.kt

Not specifically, but it's related. I'm talking about [product flavors](https://developer.android.com/build/build-variants#product-flavors) which are configured for AndroidIDE [here](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/build-logic/ide/src/main/java/com/itsaky/androidide/plugins/conf/AndroidModuleConf.kt#L62-L72).

> I've tried to publish AndroidIDE to F-Droid multiple times, but it always fails to determine the version of AndroidIDE from the source code.

The version name and version code of AndroidIDE is calculated dynamically, based on the type of commits after the previous Git tag. This is achieved using the [Nyx tool](https://github.com/mooltiverse/nyx). I'm not sure, but I think this might be the cause that the version names are not properly inferred by F-Droid.

**Comment by linsui** [comment]
> Not specifically, but it's related. I'm talking about [product flavors](https://developer.android.com/build/build-variants#product-flavors) which are configured for AndroidIDE [here](https://github.com/AndroidIDEOfficial/AndroidIDE/blob/dev/build-logic/ide/src/main/java/com/itsaky/androidide/plugins/conf/AndroidModuleConf.kt#L62-L72).

This is supported but F-Droid requires different version codes for different abis.

> The version name and version code of AndroidIDE is calculated dynamically, based on the type of commits after the previous Git tag. This is achieved using the [Nyx tool](https://github.com/mooltiverse/nyx). I'm not sure, but I think this might be the cause that the version names are not properly inferred by F-Droid.

The version name and version code can be overrided manully anyway. But for auto update we need to get it from somewhere. E.g., you can put a text file in besides the apk in github release with the version name and version code.

**Comment by itsaky** [comment]
> This is supported but F-Droid requires different version codes for different abis.

For this, I suppose we can present a number to the existing version code for each product flavor. For example version code `270` could be prepended with `1` so it becomes `1270`. Is this acceptable? Do they have any documentation for this?

> The version name and version code can be overrided manully anyway. But for auto update we need to get it from somewhere. E.g., you can put a text file in besides the apk in github release with the version name and version code.

If we just need to write the version name and version code of the APK to a file, then yes, we can do that.

I still need more information about this. Is it possible for you to contact me on [telegram](t.me/itsaky)? Or via email (see my profile for the address)?

I'll reopen this issue as #419 has been deleted for some reason.

**Comment by linsui** [comment]
> For this, I suppose we can present a number to the existing version code for each product flavor. For example version code 270 could be prepended with 1 so it becomes 1270. Is this acceptable? Do they have any documentation for this?

We support extending the version code with 1 so it becomes 2701.

> I still need more information about this. Is it possible for you to contact me on [telegram](https://github.com/AndroidIDEOfficial/AndroidIDE/issues/t.me/itsaky)? Or via email (see my profile for the address)?

I don't use telegram. I thought it's easier to discuss here but I can send you an email if you prefer that. :)

**Comment by itsaky** [comment]
> I don't use telegram. I thought it's easier to discuss here but I can send you an email if you prefer that. :)

It's okay, we can discuss here.

> This is supported but F-Droid requires different version codes for different abis.
> The version name and version code can be overrided manully anyway. But for auto update we need to get it from somewhere. E.g., you can put a text file in besides the apk in github release with the version name and version code.

Can you point me to the documentation where these things are mentioned (if there are any)? I can try to submit again with the new information.

**Comment by linsui** [comment]
There is not too much document about this (maybe I should write some about this). Basically everything is in https://f-droid.org/docs/Build_Metadata_Reference/. You can change the source code in `prebuild` so you can replace the version generator with a static code, (`$$VERSION$$` and `$$VERCODE$$`). We need to

**Comment by itsaky** [comment]
Hey @linsui, Is there a way make `fdroid build` command ignore certain maven repositories? Specifically, I want to add the following repository to ignore list :
```
https://repo.gradle.org/gradle/libs-releases/
```

This repository is required for the [Gradle Tooling API](https://docs.gradle.org/current/userguide/third_party_integration.html#sec:embedding_quickstart) which we use to run Gradle tasks in the IDE.

Also, I want to provide the Gradle build some properties (or env vars) containing the version name and version code. I tried to add Gradle properties with the `gradleprops` option, but it does not replace the `%v` or `%c` values.

Here the metadata file `com.itsaky.androidide.yml` :
```
Categories:
  - Development
License: GPL-3.0-only
WebSite: https://androidide.com
SourceCode: https://github.com/AndroidIDEOfficial/AndroidIDE
IssueTracker: https://github.com/AndroidIDEOfficial/AndroidIDE/issues
Translation: https://crowdin.com/project/androidide
Changelog: https://github.com/AndroidIDEOfficial/AndroidIDE/releases
Donate: https://androidide.com/donate/

AutoName: AndroidIDE

RepoType: git
Repo: https://github.com/AndroidIDEOfficial/AndroidIDE

Builds:
  - versionName: v2.6.1-beta
    versionCode: 261
    commit: 83a33ac3ee4bc03cd41a0f07d059f54adad5862e
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives --jre-headless -a
    init: chmod +x ../scripts/setup_fdroid_build.sh && ../scripts/setup_fdroid_build.sh $$VERSION$$ $$VERCODE$$
    gradle:
      - arm64-v8a
      - armeabi-v7a
      - x86_64
    scanignore:
      - build-logic/
      - testing/resources/
      - app/src/main/assets/data/common/android.jar
      - app/src/main/assets/data/common/gradle-wrapper.zip
      - app/src/arm64-v8a/assets/data/arm64-v8a/aapt2
      - app/src/armeabi-v7a/assets/data/armeabi-v7a/aapt2
      - app/src/x86_64/assets/data/x86_64/aapt2
      - subprojects/framework-stubs/libs/android.jar
      - termux/termux-app/src/main/cpp/bootstrap-*.zip
    gradleprops:
      - ide.build.fdroid=true
      - ide.build.fdroid.version=%v
      - ide.build.fdroid.vercode=%c

AutoUpdateMode: Version +-fdroid %v
UpdateCheckMode: HTTP
VercodeOperation:
  - 100 * %c + 1
  - 100 * %c + 2
  - 100 * %c + 3
UpdateCheckData: https://androidide.com/functions/fdroid-version-check.php|versionCode=(.*)|.|versionName=v(.*)
```

I haven't been able to perform the actual build yet, because of the repository error. I looked into the build metadata reference, but it doesn't seem to contain any information related to this issue (or at least I didn't find anything).
